name: cardano_sdk_ledger_interop
description: Part of Cardano Flutter SDK containing the data models.
version: 0.5.9
homepage: https://github.com/vespr-wallet/cardano_sdk_ledger_interop
repository: https://github.com/vespr-wallet/cardano_sdk_ledger_interop
issue_tracker: https://github.com/vespr-wallet/cardano_sdk_ledger_interop/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cardano_dart_types: # no version specified | determined by cardano_flutter_sdk version
  cardano_flutter_sdk: ^3.0.0
  ledger_cardano_plus: ^0.5.9
  meta: ^1.16.0

dev_dependencies:
  build_runner:
  lints: ^6.0.0
  pinenacl: 0.6.0
  test: ^1.25.2
  # dependency_validator: ^4.0.0
  #  mockito: ^5.4.2
  # dependency_overrides:
  # bip32_ed25519:
  #   path: ../bip32-ed25519-dart
# dependency_overrides:
#   cardano_flutter_sdk:
#     path: ../cardano_dart_sdk
# ledger_cardano_plus:
#   path: ../../ledger-cardano
# ledger_flutter_plus:
#   path: ../../ledger-flutter
